apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-admin
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "pods/exec", "pods/attach", "pods/log"]
  verbs: ["get", "list", "watch", "patch", "create", "delete"]
