apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-deployer
      nodeSelector:
        purpose: jenkins
      securityContext:
        runAsUser: 0
        fsGroup: 0
      initContainers:
      - name: init-jenkins-home
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/jenkins_home && chown -R 1000:1000 /var/jenkins_home']
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      - name: docker-installer
        image: debian:bookworm
        command: ['/bin/sh', '-c']
        args:
        - |
          apt-get update && 
          apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release &&
          mkdir -p /etc/apt/keyrings &&
          curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg &&
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null &&
          apt-get update &&
          DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-ce-cli containerd.io &&
          systemctl start docker || true
        securityContext:
          privileged: true
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50000
          name: jnlp
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        env:
        - name: JAVA_OPTS
          value: "-Xmx2048m"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /login
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc