apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-creator    # RoleBinding과 일치하도록 변경
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps", "services", "pods", "secrets"]  # secrets 추가
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
